#pragma once

enum eVehicleSeat : int {
	VS_NO_SEAT = -3,
	VS_ANY_PASSENGER = -2,
    VS_DRIVER,
    VS_FRONT_RIGHT,
    VS_BACK_LEFT,
    VS_BACK_RIGHT,
    VS_EXTRA_LEFT_1,
    VS_EXTRA_RIGHT_1,
    VS_EXTRA_LEFT_2,
    VS_EXTRA_RIGHT_2,
    VS_EXTRA_LEFT_3,
    VS_EXTRA_RIGHT_3,
    VS_NUM_SEATS
};